### ISSUE TITLE
Add delete route for styles

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-map-server#3]
`DELETE /tilesets/:id` to delete a tileset (should clear all local storage)

Qn: What about clearing storage (downloaded / cached tiles) without actually deleting the tileset? I think we might need that.

**Comment by achou11** [comment]
potentially rename issue to delete styles. eventually should support deletion of other style resources (glyphs + sprites)

initially, dont expose api for deleting tilesets, but expose api for deleting styles, which would internally delete a tileset if no other style references it (same thing for tiles)

for eventual support of deleting tiles (not necessarily tilesets), possibly restructure api so that it's `/tilesets/:tilesetId/tiles/...` so that we can support a del endpoint for tiles specifically
