### ISSUE TITLE
Add routes, api methods & e2e tests for Sprites

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-map-server#4]
A [Mapbox sprite](https://docs.mapbox.com/api/maps/styles/#sprites) consists of a single PNG with all the images used in the style, and a JSON document that describes the position of each sprite in the PNG.

- [ ] `GET /styles/:styleId/sprite{@2x}` - should return JSON sprite layout. Optional `@2x` should support retina - maybe need to support other pixel density values, but maybe just falling back to the closest that we have available offline.
- [ ] `GET /styles/:styleId/sprite{@2x}.png` - should return the PNG of the sprite

Whilst it is possible to generate the sprite dynamically from the individual symbols/images, I think it is enough for now to download the generated sprite and just use that.

We do not need update or delete routes for these, but we do need API methods to update or delete the sprite for when the style is updated or the style is deleted.

**Comment by ErikSin** [comment]
Should have a fallback: 1x

**Comment by achou11** [comment]
check mapbox gl source to see if the client ever requests 2.5x, 3x or higher. if it does, we need to be able to accept that but provide fallback with highest res we have

need 4 endpoints, but the sprite url in the style doesn't have the size + extension

probably implement so that each sprite has an id (calculated by hash of contents) and when updates occur, the sprite doesn't get cached and updates are reflected in the associated style's `sprites` field (updated url)
