### ISSUE TITLE
Support Vector Tiles

### ISSUE THREAD

**Issue by ErikSin** [digidem/mapeo-map-server#49]
## Vector Downloads
Currently map server supports Raster Tilesets only (through mbtiles files). To broaden the use case of map server, we want to be able to support Vector Tilesets, also through mbtiles files.

## To Do:
- [x] url endpoint for posting the link file path to mbtiles
- [x] Need to read mbtiles, and a space for the user to name it if there is no name
- [ ] Need code to read mbtile and metadata and determine if vector or raster
- [ ] Internal API methods to create tileset from metadata and write the tiles
- [ ] Just support reading all the data in the mbtiles
- [ ] Update based on ID

**Comment by achou11** [comment]
@gmaclennan do you mind elaborating on things that need to be implemented to support this?

**Comment by gmaclennan** [comment]
**Support Vector Tiles (through mbtiles)**

If we want to support an mbtiles file containing vector tiles, then we need a way to generate a style.json that defines how those tiles should be displayed. The mbtiles viewer does this by assigning random colours: https://github.com/mapbox/mbview/blob/master/views/layers.ejs We should be able to use the [`vector_layers`](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md#vector_layers) metadata prop from the mbtiles spec to get the info we need about vector layers.

An aside: I stumbled across this old blog post which is perhaps a helpful intro to vector tiles? https://blog.mapbox.com/whats-in-a-mapbox-studio-style-d90ee7641154

I'm not sure the use-case for this (importing vector tiles from an mbtiles file) without an option to customize the styling. @rudokemper might have thoughts on this?

**Support Vector Tiles** (in general)

This is a slightly different question. For vector tiles to work we need:

(A) A Style.json that defines how to display the tiles
(B) (not always required) Font glyphs (SDFs) _if_ the style includes labels
(C) (not always required) Sprites (PNG + JSON) _if_ the style includes icons

If we want vector tiles to work while the user is online, then we just need to store the style.json and keep the URLs that point to tiles/sources, glyphs and sprites the same.

If we want vector tiles to work offline, then we need to download the tiles, glyphs and sprites (or possibly serve alternative glyphs that we have locally).

When the user adds a style.json, then we could:

1. Create the tileset (often needs internet to download the tilejson referenced in the style)
2. Download the sprite PNG + JSON

Downloading tiles + glyphs at creation seems like too much, since it will take a while.

If we cache tiles the user accesses, and replace glyphs with locally-available alternatives, then the user can have an offline map for areas they visit while online (e.g. areas the tiles are cached for).

For a fully offline vector map experience, then we need to either:

A. Offer a way for the user to download tiles within a bounding box and zoom range
B. Offer a way to import a file containing the Style, Tiles, Glyphs and Sprites

**Comment by rudokemper** [comment]
The use case that I can think of: a user has an unstyled mbtiles file that they want to use in Mapeo. There is precedent for this: ODK [currently permits users to add an offline map using an mbtiles file](https://docs.getodk.org/collect-offline-maps/) without a style.json file. Instead, the app [assigns a random color](https://github.com/getodk/collect/blob/c9655a27b73c8c09178f50ee6e4c50f953ec847d/mapbox/src/main/java/org/odk/collect/mapbox/MapboxMapFragment.kt#L529) to distinguish the layers.

Another thought is that some of our own current users know how to generate a vector mbtiles file using QGIS. It's currently quite tricky to style an mbtiles file*, so allowing them to upload vector mbtiles and assigning random colors could be a good way to enable them to use their own data in Mapeo without much accompaniment. 

*Maputnik is still the best option as far as I know?

**Comment by achou11** [comment]
> Support Vector Tiles (in general)
> 
> This is a slightly different question. For vector tiles to work we need:
> 
> (A) A Style.json that defines how to display the tiles
> (B) (not always required) Font glyphs (SDFs) if the style includes labels
> (C) (not always required) Sprites (PNG + JSON) if the style includes icons

@gmaclennan seems like most of this will be in place once #54 is merged. from what i can tell, there isn't any special handling of what we provide to the client in terms of style, sprites, glyphs, etc. compared to a raster-based style right? The only difference is that the tilesets referenced by the style will be pointing to different tiles under the hood - whether it's getting the upstream `pbf`-formatted tile response or the locally stored `pbf`-formatted tile data


>  assigning random colors could be a good way to enable them to use their own data in Mapeo without much accompaniment.

@rudokemper i like the sound of that from a dev perspective - curious about potential visual issues and if we need to account for that (besides just choosing a safe palette)

**Comment by achou11** [comment]
@gmaclennan  Going to claim that this can be closed after merging the imports pr. Feel free to reopen if otherwise!
